# frozen_string_literal: true

require "bundler/gem_tasks"
require "fileutils"
require "rake/extensiontask"
require "rspec/core/rake_task"
require "yard"

Rake::ExtensionTask.new("ublk") do |ext|
  ext.lib_dir = "lib/ublk"
end

YARD::Rake::YardocTask.new

namespace :test do
  RSpec::Core::RakeTask.new(:unit) { |task| task.pattern = "spec/unit/**/*_spec.rb" }
  RSpec::Core::RakeTask.new(:system) { |task| task.pattern = "spec/system/**/*_spec.rb" }
end

namespace :gen do
  desc "Regenerate Ruby constants from the installed Linux ublk headers"
  task :constants do
    executable = "tmp/dump_ublk_constants"
    FileUtils.mkdir_p("tmp")
    sh RbConfig::CONFIG.fetch("CC"), "-Iext/ublk", "tools/dump_constants.c", "-o", executable
    names = IO.popen([executable], &:read).lines.map { |line| line.split("=", 2).first }
    body = names.map { |name| "  UBLK_CONST(#{name});" }.join("\n")
    File.write("ext/ublk/constants.c", <<~C)
      /* Generated by rake gen:constants. */
      #include "internal.h"

      #define UBLK_CONST(name) rb_define_const(ublk_native_module, #name, ULL2NUM(name))

      void ublk_init_constants(void)
      {
      #{body}
      }
    C
  end
end

task default: "test:unit"
