/* Generated by rake gen:constants. */
#include "internal.h"

#define UBLK_CONST(name) rb_define_const(ublk_native_module, #name, ULL2NUM(name))

void ublk_init_constants(void)
{
  UBLK_CONST(UBLK_F_USER_COPY);
  UBLK_CONST(UBLK_F_CMD_IOCTL_ENCODE);
  UBLK_CONST(UBLK_F_USER_RECOVERY);
  UBLK_CONST(UBLK_MAX_QUEUE_DEPTH);
  UBLK_CONST(UBLKSRV_IO_BUF_OFFSET);
  UBLK_CONST(UBLK_IO_OP_READ);
  UBLK_CONST(UBLK_IO_OP_WRITE);
  UBLK_CONST(UBLK_IO_OP_FLUSH);
  UBLK_CONST(UBLK_IO_OP_DISCARD);
  UBLK_CONST(UBLK_IO_OP_WRITE_ZEROES);
}
