name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-24.04
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'

    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install native dependencies
        run: sudo apt-get update && sudo apt-get install -y liburing-dev
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Compile and test
        run: bundle exec rake compile test:unit
      - name: Validate RBS
        run: bundle exec rbs validate
      - name: Build gem
        run: bundle exec rake build
